### ISSUE TITLE
Error on db install

### ISSUE THREAD

**Issue by sgc-fireball** [redkite-labs/InstallerBundle#3]
``` php
        $query = 'DROP DATABASE IF EXISTS `' . $this->database . '`';
        $result = $orm->executeQuery($query);

        $query = 'CREATE DATABASE `' . $this->database . '`';
        $result = $orm->executeQuery($query);
```

Please use backticks `in your mysql commands.
If the database name is red-kite mysql throws an error without`

**Comment by janxin** [comment]
@sgc-fireball  RedKite CMS 2 does not require a database, so this bundle is deprecated and this issue is closed. https://github.com/redkite-labs/RedKiteCms.

Anyway, thank you very much for reporting this problem.
